version: "3.7"

services:
  www_picoluna_com:
    build:
      context: .
      dockerfile: ./Dockerfile
      target: development
    image: www_picoluna_com:latest
    environment:
      NODE_ENV: "development"
      APP_PORT: 8000
      REDIS_HOST: www_picoluna_com_redis
      REDIS_PORT: 6379
      MYSQL_HOST: www_mysql_5
      MYSQL_PORT: 3306
      MYSQL_USER: "root"
      MYSQL_PWD: "123456"
      MYSQL_DB_NAME: "www_picoluna_com"
    expose:
      - "8000"
    ports:
      - "8000-8001:8000"
    networks:
      - webnet
    restart: always
    volumes:
      - "/data/app/www.picoluna.com/app:/data/app/www.picoluna.com/app"
      - "/data/log/www.picoluna.com:/data/log/www.picoluna.com"
    depends_on:
      - www_picoluna_com_redis
    init: true
  www_picoluna_com_redis:
    image: redis:alpine
    restart: always
    networks:
          - webnet
networks:
  webnet:
#    external: true
    name: webnet
    driver: bridge
