version: "3.7"

services:
  www_picoluna_com:
    build:
      context: .
      dockerfile: ./Dockerfile
      target: development
    image: www_picoluna_com:latest
    environment:
      NODE_ENV: "development"
      APP_PORT: 8000
    ports:
      - "8000-8001:8000"
    networks:
      - webnet
    restart: always
    deploy:
      replicas: 2
      update_config:
      restart_policy:
        condition: any
        delay: 5s
        max_attempts: 5
        window: 10s
      update_config:
        parallelism: 1
        delay: 5s
    volumes:
      - "/data/app/www.picoluna.com/app:/data/app/www.picoluna.com/app"
      - "/data/log/www.picoluna.com:/data/log/www.picoluna.com"
networks:
  webnet:
#    external: true
    name: webnet
    driver: bridge
